broadinstitute/cromshell

cromwell
using a version of curl newer than curl ~7.43.0 would cause cromshell submit to fail silently
this was due to curl failing when a -F argument was given an empty filename
fixes #5
=> making cromshell compatible with newer curl

README.md, cromwell
Altered behavior to retain default CROMWELL_URL but allow overriding
it by setting CROMWELL_URL as env var.
This resolves the FIXME comment previously at this location.
=> Allow override of CROMWELL_URL

cromshell
- Now keeps track of what cromwell server you run on
- Moved workflow id folders to $CROMSHELL_CONFIG_DIR
- Changed structure of data stored in $CROMSHELL_CONFIG_DIR
- Updated default cromwell server to v36
- Added the `list` command to show what you've run before
Fixes #16
=> Now keeps track of what cromwell server you run on.

cromshell
When my CROMWELL_URL is "http://localhost:8000",  the ":8000" string should be trimed.
=> fix ping url

cromshell
Cromwell by default does not return subworkflow metadata, probably to cut down on size (I believe you need to enter the subworkflow id to get it, which is a huge pain if you have many subworkflows). Luckily it can be done with the API if you pass this extra parameter `expandSubWorkflows=true`. This PR enables this behavior. What do you guys think?
=> Expand subworkflow metadata

README.md, cromshell
* Added logic to submit to prevent adding errored jobs to list.
* Reworked how logo is displayed for failures.
* Fixed case sensitivity when asking user for input.
* Now tries to use `dialog` and falls back to basic text input if dialog
is not installed.
* Fixed the notification daemon to work with the server file.
Fixes #17
=> Added in basic first-time run config.

cromshell
Printing subcommand status message to stderr instead of stdout so it doesn't interfere with piping json output
fixes https://github.com/broadinstitute/cromshell/issues/60
=> Printing subcommand to sdterr instead of stdout

cromshell
This function would not work on my local because the job was too large for cromwell to give a timely response. Similar logic could be put in many subcommands probably. 
And reduce nesting of output, I changed the output syntax to reduce unnecessary (i think?) nesting.
=> Increase performance of execution-status-count

README.md, cromshell
As I've been hacking away at ExomeJointGenotyping, I scripted a way to get a nice, human-readable summary of a workflow's state. It was implemented in my own cromwell client script since cromshell (at least to my knowledge) doesn't communicate with authenticated cromwell servers. I noticed the cromshell has an `execution-status-count` subcommand, but its output is JSON, which is great for computers, but not necessarily for humans (or turtles). I've added a `-p` flag which prettifies the output of `execution-status-count`, resulting in a much nicer, color-coded, compact readout of the executionStatus of a workflow. The `-x` flag will expand sub-workflows, which gives a longer output, but details tasks in a subworkflow.
Let me know if you're interested in this feature!
=> Pretty execution-status-count implementation

README.md, cromshell
The way the arguments were being parsed changed with the last PR.  This broke negative (relative) job ID handling. 
I pushed the argument handling for `execution-status-count` into that function (like with other functions that take arguments) and now it all works again.  I also updated the README and help information to better reflect the new options for this argument.
I've added comments to steer things better in the future.
Fixes #73
=> Fixed regression of relative job ID failure.

cromshell
Submitting with dependencies is broken due to a typo. This should fix it.
=> Fix submitting with dependencies

cromshell
Should fix issues associated with port numbers and server existence as a corollary.
=> Now directly queries the cromwell instance to prove it exists.

cromshell
When trying to `execution-status-count -p` nested workflows, the readonly variable would cause cromshell to error out.
=> Fixing small bug with nested subworkflows

cromshell
* We accidentally were checking the wrong status for 'Failed' which caused us to falsely identify workflows with retryable failures as doomed.
* Partial fix for https://github.com/broadinstitute/cromshell/issues/105
=> Fix false positive doom.

cromshell
* This fixes a case where we would fail to mark doomed workflows as doomed.
* Partial fix https://github.com/broadinstitute/cromshell/issues/105
* We now require jq 1.5
=> Update jq query to understand subworkflows

completions/_cromshell
* Adding a completion script for zsh.
* It's fairly complete and completes all the current arguments in a relatively sane way.
* It attempts to complete workflow aliases/ids based on a hardcoded path to the cromshell data tsv.
=> Add zsh completion script

cromshell
to handle workflows that executed under now-retired cromwell servers.
The culprit is [this line](https://github.com/broadinstitute/cromshell/blob/d144f0b7a9f1361bbdd0a2477b63defda39f83d8/cromshell#L1138) which acted as a blackhole: if one line in the TSV has a cromwell server that is now retired (or even temporarily unreachable), the blockhole eats the error message, leaving us with no clue that all entries in the TSV below that line is NOT updated.
=> update list function, 

README.md, completions/_cromshell, cromshell
* You can now use the alias counts instead of execution-status-count which is much shorter.
=> Add counts as shorter alias of execution-status-count

cromshell
* make aliases work correctly with execution-status-count and notify
* fixes https://github.com/broadinstitute/cromshell/issues/118
=> Enable alias matching for non-standard form commands

cromshell
This effectively bandages the issue of not being able to use the
notification daemons on Broad filesystems because IT won't upgrade our
version of JQ.
Any other systems that don't have a modern version of JQ are now capable of running the `notify` daemon as well.
=> Excluded the notify daemon from the jq version check.

cromshell
- GNU grep doesn't like to work with tabs, so it wasn't properly parsing
the aliases out.  Removed the offending grep command so aliases can be
pulled from the TSV file on linux.
- Fixes #135
=> Fixing issue with aliases and GNU grep.

src/cromshell/status/command.py, src/cromshell/utilities/cromshellconfig.py, src/cromshell/utilities/http_utils.py
Updated api string variable in the cromshell config, http utility, and status file. The update involves removing the ending "/" at initial declaration of the variable and asks functions that use the variable to add the forward slash along with their needed extension. This enables cromshell api commands like the submit function which does not use additional extensions to use the variable without having to remove the forward slash.
=> Updated api_string variable

README.md, cromshell
Absolutely feel free to shoot this down...
I was wanting to update my cromwell server in cromshell, and I always forget where the config file is located.  I thought it might be nice to have a sub-command which takes care of this.
I tried to make the smallest possible change in the code, so it might not be the most elegant solution... I've just reached in and set `CROMWELL_NEEDS_SETUP=true` if the new `update-server` sub-command is run, which should trigger the setup code that already exists.  Does that seem like an acceptable strategy?
=> Add the sub-command "update-server"

cromshell
- This fixes an issue found where cromshell was filling /tmp disk space
with the `notify` daemon.  Not 100% sure why the trap didn't catch the
temp files, but this is a fix for the issue.
=> Minor change to remove temp files in the notify helper.

cromshell
* timing was putting an extra "http" into the url which caused it to not load correctly.
* fixes https://github.com/broadinstitute/cromshell/issues/167
=> Fix timing command

README.md
I just went through the process of getting `cost` to work. I was getting the following error at first:
```
$(standard_in) 1: parse error
(standard_in) 1: illegal character: Q
(standard_in) 1: illegal character: :
```
which was apparently due to not having a default cloud project set for `bq`. I've added a note about this in the README.
=> Add note about bq init to README

src/cromshell/status/command.py
Previously, requests call in the status command used a string constant from the cromshell utilities script to obtain the metadata for a workflow. Since the addition of the metadata command, the string constant has been updated to a dictionary. Thus when the requests line in the status command tries to use the old string it fails. In this PR the status command requests call has now been updated to properly use the constant in dictionary form.
=> Fix requests metadata call 

setup.py
Removed dataclasses from the setup.py because starting with python3.7, the package is included with python releases. ([reference](https://pypi.org/project/dataclasses/)). Cromshell only supports >=3.7
=> removed dataclasses in setup.py 

.github/workflows/unit_tests.yml
Unit test is currently only using python 3.9 when running unit tests. This is due to the womtool step altering the python environment version. This pr shifts the womtool setup step before the python setup step so that the correct python version is being used before running the unit test scripts.
=> Shifted womtool installation to be the second step in git unit test workflow

cromshell
- Fixed problem in task parsing where if a task had the word `Failed` in
it, it would be labeled as a failing task regardless of status.
=> Fixing issue where tasks would be incorrectly labeled as failed.

src/cromshell/utilities/http_utils.py
For my feature I am communicating with a server that requires auth and I added this code to make my life easier.
Looks like this:
```
2022-04-29 11:54:35,728 cromshell.utilities.http_utils             ERROR    Error: Cannot communicate with Cromwell server: https://leonardo.dsde-dev.broadinstitute.org/proxy/google/v1/apps/terra-dev-a2f0413e/terra-app-69e7caa2-993d-4a88-bc33-31f378bb9bd5/cromwell-service due to error: 
b'{"source":"leonardo","message":"Your account is not authenticated","statusCode":401,"exceptionClass":"class org.broadinstitute.dsde.workbench.leonardo.model.AuthenticationError","traceId":null}'
```
=> Add error detail to when server communication fails

src/cromshell/__main__.py, src/cromshell/abort/command.py, src/cromshell/metadata/command.py, src/cromshell/status/command.py, src/cromshell/submit/command.py, src/cromshell/utilities/cromshellconfig.py, src/cromshell/utilities/http_utils.py, tests/unit/test_cromshellconfig.py, tests/unit/test_http_utils.py
This is in support of communicating with Cromwells that require authentication, such as:
1. Cromwells configured with a CromIAM instance in front
- Requires auth header
2. "Cromwell as an app" running in a Terra workspace
- Requires auth header and referer URL
- Server URL looks like `https://leonardo.dsde-dev.broadinstitute.org/proxy/google/v1/apps/terra-dev-a2f0413e/terra-app-69e7caa2-993d-4a88-bc33-31f378bb9bd5/cromwell-service` because requests to Cromwell go via the Leonardo proxy
- Referer looks like `https://leonardo.dsde-dev.broadinstitute.org`
=> BW-1226 Add `referer_header_url` and `gcloud_token_email` options

cromshell
Broad / DSP users will still need to change their cost table to the new, correct one.
=> Fixes `cost` and `detailed cost` queries for new billing setup as of 2022 Aug 11

src/cromshell/utilities/config_options_file_utils.py
Cromshell checks both the command parameters and config file for the following Cromwell auth parameters `gcloud_token_email` and `referer_header_url`, so adding them to the config template
=> Added cromwell auth parameters to cromshell config template

src/cromshell/__main__.py, src/cromshell/counts/command.py, src/cromshell/metadata/command.py, src/cromshell/utilities/cromshellconfig.py, src/cromshell/utilities/io_utils.py, tests/unit/test_counts.py, tests/unit/test_io_utils.py
- Centralized json coloring setting to cromshellconfig.py, 
- Added option to disable coloring in main command
- By default json coloring is true
- JSON coloring is disabled if the output is pipped to file
=> Add option to not color json output to main command

README.md, requirements.txt, src/cromshell/__main__.py, src/cromshell/cost/command.py, src/cromshell/counts/command.py, src/cromshell/metadata/command.py, src/cromshell/slim_metadata/command.py, src/cromshell/status/command.py, src/cromshell/submit/command.py, src/cromshell/utilities/config_options_file_utils.py, src/cromshell/utilities/cromshellconfig.py, src/cromshell/utilities/workflow_id_utils.py, src/cromshell/utilities/workflow_status_utils.py, tests/integration/test_abort.py, tests/integration/utility_test_functions.py, tests/unit/mock_data/running_helloworld_metadata.json, tests/unit/mock_data/submitted_helloworld_metadata.json, tests/unit/mock_data/succeeded_helloworld_metadata.json, tests/unit/test_cost.py
The cost command will provide the cost for running a workflow, and have a "detailed" option that breaks down the cost per task of a workflow
=> Add cost command

src/cromshell/__main__.py, tests/conftest.py, tests/integration/test_version.py, tests/unit/test_version.py
The version command currently only displays the version of cromshell through Logger.info, but the logger by default is set to show only warnings/errors. 
This fix is to have the version command `print` the version and add unit/integration test for the command.
=> Version Command fix

README.md
Fix the installation commands that we forgot to update when we merged 2.0.0
=> Fix out of date (un)installation commands

pyproject.toml, src/cromshell/metadata/command.py, src/cromshell/slim_metadata/command.py
Problem:
adding the `-mc` option will still print a color-highlighted version of a json. 
Change: 
removed `add color` setting for the pretty print json function for metadata and slim-metadata command
=> Bug fix for printing machine readable json for metadata and slim-metadata
