README.md, cromwell
slim_metadata -> slim-metadata
executionStatusCount -> execution-status-count
=> normalize command names

LICENSE
We probably should have this..
=> add BSD license

README.md, cromshell
updating the help and readme to be more useful and up to date
=> update the help and readme

cromshell
* this lets you do cromshell list when offline
* fixed typo
=> only check for the server when necessary

cromshell
@jonn-smith I made it a status indicator turtle...
=> turtle status

cromshell
The turtle has invaded metadata output in stdout, and I can't find any place where he really needs to be there. This moves him to stderr where he (read I) will be happier.
=> Print turtle to stderr

cromshell
I don't know if turtles turn upside down when they die, but this makes it easier to recognize failures.
=> Dramatic dead turtle

cromshell
Could not remove all other arg parsing due to positional args.
Fixed #43 - Twyseturtles was due to the `notify` logic.
Fixed #42 
@lbergelson - I tested it reasonably well locally, but it could definitely use more testing.  In particular, `submit`, `notify`, and `list` (but really a little of everything).
=> Refactored to use getopts in some places.

README.md
Minor fix to the readme for workflow ID compatibility.
=> Updated readme to reflect new behavior for workflow ids.

cromshell
=> preventing error message when invoking cromshell with no args

README.md, cromshell
-w flag will wait for status to change from `Submitted` to anything
else before the script exits.
The flag causes some interactive messages on the terminal.
Fixes #49
=> Added in -w flag for submit command.

README.md, cromshell
Added in -t flag for CURL timeouts.
Fixes #53
=> Curl timeouts

cromshell
Some debugging code seems to have been left in from last PR and a commented out line should have been enabled (it's analog should have been removed).
Fixes #55
=> Fixed issue with notify daemon.

cromshell
=> red dead turtle

cromshell
No longer will rogue turtles plague the terminals of our future selves.
Fixes #58
=> Added in protections to kill the turtleSpinner on exit.

cromshell
=> Fixed issue with list-outputs.

cromshell
Important turtle fix for issue reported by @yfarjoun
=> Improve turtle shell pattern stability under moving conditions

cromshell
Check that file inputs exist and are not empty.
Addresses #75  #8
=> checking existence of files

cromshell
- fixed the ability to have multiple states (-s) in cleanup
- print out records to be removed before removing them
=> tidy up code in cleanup function

cromshell
fixed non-pretty output for lists of workflow IDs
fixed issue with parsing the relative workflow IDs.
Fixes #79
=> Fixed error in execution-status-count with relative IDs.

cromshell, resources/options.json, testing/helloWorld.json, testing/helloWorld.wdl, testing/will_fail.json, testing/will_fail.wdl
Added a status to indicate if an in-progress workflow will fail.
Also updated some colors.
Fixes #78
=> Added in a WILL_FAIL status for workflows that will fail.

README.md, cromshell
I've done several different minor refactoring steps here, each is in it's own commit.
1.  alias curl to include the timeouts
2. remove some extraneous code from turtle
3. fix some typos
4. autofix the intellij complains about single bracket if statements and `{}` around variables
=> Various cleanup refactoring

README.md, cromshell
=> Added womtool validation for WDL/JSON if it's in your path.

cromshell
sometimes I want to know the start and end time.
=> allow custom slim-metadata parameters

cromshell
=> Improve on the name WILL_FAIL

README.md, cromshell, testing/workflows/gpu_cuda_test.json, testing/workflows/gpu_cuda_test.wdl
- Added in a new logo for tasks with the status DOOMED.
- Fixes #89
=> Adding in functionality for aliasing jobs.

cromshell
It broke when aliases were added.
=> Fixing cleanup command.

cromshell
=> Adding server name to submit command output.

src/cromshell/status/command.py, src/cromshell/utilities/cromshellconfig.py
Fix to be able to itterate through workflow metadata to obtain subworkflow statuses
=> Fix to be able to iterate through workflow metadata to check subworkflow failures

src/cromshell/__main__.py, src/cromshell/status/command.py, src/cromshell/utilities/cromshellconfig.py, src/cromshell/utilities/http_utils.py, tests/unit/test_cromshellconfig.py
Added timeout (5 sec) and check certs (True) defaults for 'requests'. 
Added the parameters to change them in command line
=> Add Requests Defaults and Parameters

src/cromshell/__main__.py, src/cromshell/abort/command.py, src/cromshell/utilities/http_utils.py
=> Bs add abort function

.github/workflows/main.yml, setup.py, src/cromshell/log.py, src/cromshell/status/command.py, src/cromshell/submit/command.py, src/cromshell/utilities/cromshellconfig.py, src/cromshell/utilities/http_utils.py, src/cromshell/utilities/io_utils.py, tests/unit/test_cromshellconfig.py, tests/unit/test_submit.py
Adding yml file to automate unit tests and linting through git actions
=> Add git actions tests

cromshell
More cleanup for notify daemon processes.
=> Removing another temporary file from notify daemon.

README.md, cromshell
Added in two new commands to get the cost of workflows run on Google Cloud Platform.
Requires a new config file to be created in the `~/.cromshell` folder (`gcp_bq_cost_table.config`).
=> Added cost commands.

completions/_cromshell
Adding the missing completions.
=> Adding zsh completions for cost commands

README.md, completions/_cromshell, completions/reload.sh
Add a forgotten command to the completions and reformat the readme a bit.
Add a script to reload the completions file locally for testing.
=> Readme and completions update

README.md, src/cromshell/__main__.py, src/cromshell/alias/command.py, src/cromshell/status/command.py, src/cromshell/utilities/cromshellconfig.py, src/cromshell/utilities/io_utils.py, src/cromshell/utilities/submissions_file_utils.py, src/cromshell/utilities/workflow_id_utils.py, tests/conftest.py, tests/integration/conftest.py, tests/integration/mock_data/all.workflow.database.tsv, tests/integration/test_alias.py, tests/integration/utility_test_functions.py, tests/unit/conftest.py, tests/unit/test_alias.py, tests/unit/test_cromshellconfig.py, tests/unit/test_io_utils.py, tests/unit/test_submissions_file_utils.py, tests/unit/test_workflow_id_utils.py
Added Alias command
Added workflow_id_utils script to hold functions getting, validating, or manipulating workflow_id
Added conftest.py to centralize pytest fixtures
Added Brew installation instructions to ReadMe
Made all_workflow_database.tsv header variable an Enum
=> Added Alias command and scripts for workflow_id utils

MANIFEST.in, requirements.txt, setup.py
Pinned requirements, minor clean ups and convention adjustments
=> setup.py adjustments

README.md
`CROMSHELL_DIR` to `CROMSHELL_CONFIG`
=> readme referred to wrong env name

README.md
* add a note about cromshell 2 alpha to the master branch readme so people know it exists and how to find it.
=> Add note about cromshell 2 alpha to readme

src/cromshell/__main__.py, src/cromshell/update_server/command.py, src/cromshell/utilities/cromshellconfig.py, tests/integration/test_update_server.py
Command that will update the default Cromwell server for future workflow submissions.
Closes #199
=> Add `update-server` command to 2.0

dev-requirements.txt, src/cromshell/__main__.py, src/cromshell/logs/command.py, src/cromshell/metadata/command.py, src/cromshell/utilities/io_utils.py, test-requirements.txt, tests/unit/mock_data/logs/fail_Mutect2.json, tests/unit/mock_data/logs/success.json, tests/unit/mock_data/logs/will_fail.json, tests/unit/test_logs.py
By default it lists failed logs only. Optionally it can expand the logs with GCS or get non-failed logs as well
=> Added a 'logs' command for listing all of the logs. 

requirements.txt
@jamesemery , should there be a specific version required?
=> Add `gcsfs` to requirements.txt

.github/workflows/pypi_packaging.yml, MANIFEST.in, README.md, developer_docs/addcommand.md, pyproject.toml, setup.py, src/cromshell/__main__.py, tests/integration/utility_test_functions.py
Adding scripts to publish cromshell to pypi
Changed call from "cromshell-alpha" to "cromshell-beta"
Updated Readme to show what commands are available in cromshell 2
=> scripts to publish to pypi 2

tests/unit/test_io_utils.py
added a unit test (address Berr's comment from my last PR)
=> add unit test (address Berri's comments from PR)

.github/workflows/pypi_packaging.yml, developer_docs/publish_release.md
Added docs detailing how to publish cromshell releases to brew and pypi
Edited pypi git action so that build happens after final edits to toml file
=> Add publish release docs

README.md, src/cromshell/validate/command.py
Added validation section to README.md
Added error logic if womtool and miniwdl are disabled at the same time
Added function to check connection with cromwell server
=> Minor updates to validation command
